INSERT INTO burgers VALUES("hamburger", "TRUE"),
INSERT INTO burgers VALUES("cheeseburger", "TRUE"),
INSERT INTO burgers VALUES("double cheeseburger", "FALSE"),
INSERT INTO burgers VALUES("bacon cheeseburger", "TRUE"),
INSERT INTO burgers VALUES("jalepino cheeseburger", "FALSE"),
INSERT INTO burgers VALUES("patty melt", "FALSE"),
INSERT INTO burgers VALUES("steak sandwhich", "FALSE"),
INSERT INTO burgers VALUES("bbq burger", "FALSE"),
